name: Build with Maven

on:
  push:
    branches: [ dev ]  # Change "main" to your main branch name if different
  pull_request:  # Optional: Trigger on pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Or another desired runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout your code from the repository

      - name: Set up JDK 17  # Change version if needed
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven  # Optionally cache Maven packages

      - name: Build with Maven
        working-directory: ./javaparser-maven-sample-master
        run: mvn -B clean install
